# Generated by Django 5.0.6 on 2024-05-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proizvod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('deskripcija', models.TextField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kolicina', models.IntegerField()),
                ('napravljen', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
